pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('Build maven') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/TinyAntu/PrestaBanco_App_Monolitica.git']])
                dir('Prestabanco-backend') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('Prestabanco-backend') {
                    bat 'mvn test'
                }
            }
        }

        stage('Build docker image') {
            steps {
                script {
                    bat 'docker build -t tinyantu/prestabanco-backend:latest -f Prestabanco-backend/Dockerfile Prestabanco-backend'
                }
            }
        }

        stage('Push image to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dckhubpassword', variable: 'dhpsw')]) {
                        bat 'docker login -u tinyantu -p %dhpsw%'
                    }
                    bat 'docker push tinyantu/prestabanco-backend:latest' 
                }
            }
        }
    }
}
